# For reference only - this Secret deployed via ansible
apiVersion: v1
kind: Secret
metadata:
  name: eightbitsaxlounge-chat-secrets
  namespace: eightbitsaxlounge
  labels:
    app: eightbitsaxlounge
    component: chat
type: Opaque
stringData:
  client-id: "placeholder"
  client-secret: "placeholder"
  midi-client-id: "placeholder"
  midi-client-secret: "placeholder"
