name: State Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - state/*
    paths:
      - 'state/version.txt'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  release:
    name: Release State Component
    permissions:
      packages: write
      security-events: write
    uses: ./.github/workflows/release-template.yaml
    with:
      component: 'state'
      test-target: 'test'
      build-target: 'build'
      deploy-target: 'deploy'
      requires-docker-login: true
    secrets:
      component-secrets: |
        {
          "SYSTEM_PASS": "${{ secrets.STATE_SYSTEM_PASS }}",
          "OVERLAY_PASS": "${{ secrets.STATE_OVERLAY_PASS }}",
          "CHAT_PASS": "${{ secrets.STATE_CHAT_PASS }}",
          "MIDI_PASS": "${{ secrets.STATE_MIDI_PASS }}",
          "DATA_PASS": "${{ secrets.STATE_DATA_PASS }}"
        }
